Microsoft.EntityFrameworkCore.WebApplication/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Microsoft.EntityFrameworkCore.WebApplication.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Microsoft.EntityFrameworkCore.WebApplication/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.PersistenceApi;

namespace Microsoft.EntityFrameworkCore.WebApplication.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        public IReadOnlyCollection<Order> FilteredOrders;
        public IReadOnlyCollection<Order> AllOrders;
        public IReadOnlyCollection<Order> SkipAndTakeOrders;
        public IPagedList<Order> PagedList;
        public Order? Order;


        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task OnGetAsync(int? pageNum = 1)
        {
            var orderRepository = _unitOfWork.GetRepository<IOrderRepository>();
            FilteredOrders = await _unitOfWork.Queryable<Order>().Where(OrderFilters.NameFilter).OrderByDescending(b => b.AddedAt).ToListAsync();
            AllOrders = await _unitOfWork.Queryable<Order>().ToListAsync();
            SkipAndTakeOrders = await orderRepository.GetAsync(o => !o.IsDeleted, skip: 1, take: 2);
            Order = _unitOfWork.Queryable<Order>().FirstOrDefault(q => q.Name.Contains("World"));
            PagedList = await _unitOfWork.Queryable<Order>().OrderBy(o => o.Name).ToPagedListAsync(pageNum.Value, 5);
        }

        public async Task<IActionResult> OnPostAddAsync(string name)
        {
            _unitOfWork.GetRepository<IOrderRepository>().Add(new Order(name));
            await _unitOfWork.SaveChangesAsync();

            return Redirect("./Index");
        }

        public async Task<IActionResult> OnPostDeleteAsync(Guid id)
        {
            var orderRepository = _unitOfWork.GetRepository<IOrderRepository>();
            var order = orderRepository.GetById(id);
            orderRepository.Remove(order);
            await _unitOfWork.SaveChangesAsync();

            return Redirect("./Index");
        }

        public async Task<IActionResult> OnPostSoftDeleteAsync(Guid id)
        {
            var orderRepository = _unitOfWork.GetRepository<IOrderRepository>();
            var order = orderRepository.GetById(id);
            order.IsDeleted = true;
            order.DeletedAt = DateTime.UtcNow;
            await _unitOfWork.SaveChangesAsync();

            return Redirect("./Index");
        }
    }
}

Microsoft.EntityFrameworkCore.WebApplication/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="row" style="padding: 30px;">
    <div class="col-12 mb-3">
        <h4>New order</h4>
        <form method="post" asp-page-handler="Add">
            <input type="text" name="name" class="form-control mb-1" />
            <input type="submit" class="btn btn-primary" />
        </form>
    </div>

    <div class="col-12 mb-3">
        <h4>The first order having "World" name</h4>

        <table class="table">
            <thead>
                <tr>
                    <th style="padding-right: 10px;">ID</th>
                    <th style="padding-right: 10px;">Name</th>
                    <th style="padding-right: 10px;">AddedAt</th>
                    <th style="padding-right: 10px;">Functions</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Order != null)
                {
                    <tr>
                        <td style="padding-right: 10px;">@Model.Order.Id</td>
                        <td style="padding-right: 10px;">@Model.Order.Name</td>
                        <td style="padding-right: 10px;">@Model.Order.AddedAt</td>
                        <td style="padding-right: 10px;">
                            <form method="post" asp-page-handler="Delete">
                                <input type="hidden" name="id" value="@Model.Order.Id" />
                                <input type="submit" value="Delete" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-12 mb-3">
        <h4>Orders having "Hello" name</h4>
        <table class="table">
            <thead>
                <tr>
                    <th style="padding-right: 10px;">ID</th>
                    <th style="padding-right: 10px;">Name</th>
                    <th style="padding-right: 10px;">AddedAt</th>
                    <th style="padding-right: 10px;">Functions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.FilteredOrders)
                {
                    <tr>
                        <td style="padding-right: 10px;">@item.Id</td>
                        <td style="padding-right: 10px;">@item.Name</td>
                        <td style="padding-right: 10px;">@item.AddedAt</td>
                        <td style="padding-right: 10px;">
                            <form method="post" asp-page-handler="Delete">
                                <input type="hidden" name="id" value="@item.Id" />
                                <input type="submit" value="Delete" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-12 mb-3">
        <h4>All orders</h4>
        <table class="table">
            <thead>
                <tr>
                    <th style="padding-right: 10px;">ID</th>
                    <th style="padding-right: 10px;">Name</th>
                    <th style="padding-right: 10px;">AddedAt</th>
                    <th style="padding-right: 10px;">Functions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.AllOrders)
                {
                    <tr>
                        <td style="padding-right: 10px;">@item.Id</td>
                        <td style="padding-right: 10px;">@item.Name</td>
                        <td style="padding-right: 10px;">@item.AddedAt</td>
                        <td style="padding-right: 10px;">
                            <form method="post" asp-page-handler="Delete" style="display: inline">
                                <input type="hidden" name="id" value="@item.Id" />
                                <input type="submit" value="Hard Delete" />
                            </form>
                            <form method="post" asp-page-handler="SoftDelete" style="display: inline">
                                <input type="hidden" name="id" value="@item.Id" />
                                <input type="submit" value="Soft Delete" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-12 mb-3">
        <h4>Orders Skip & Take</h4>
        <table class="table">
            <thead>
                <tr>
                    <th style="padding-right: 10px;">ID</th>
                    <th style="padding-right: 10px;">Name</th>
                    <th style="padding-right: 10px;">AddedAt</th>
                    <th style="padding-right: 10px;">Functions</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.SkipAndTakeOrders)
                {
                    <tr>
                        <td style="padding-right: 10px;">@item.Id</td>
                        <td style="padding-right: 10px;">@item.Name</td>
                        <td style="padding-right: 10px;">@item.AddedAt</td>
                        <td style="padding-right: 10px;">
                            <form method="post" asp-page-handler="Delete" style="display: inline">
                                <input type="hidden" name="id" value="@item.Id" />
                                <input type="submit" value="Hard Delete" />
                            </form>
                            <form method="post" asp-page-handler="SoftDelete" style="display: inline">
                                <input type="hidden" name="id" value="@item.Id" />
                                <input type="submit" value="Soft Delete" />
                            </form>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-12 mb-3">
        <h4>Paged List</h4>
        <table class="table">
            <thead>
            <tr>
                <th style="padding-right: 10px;">ID</th>
                <th style="padding-right: 10px;">Name</th>
                <th style="padding-right: 10px;">AddedAt</th>
                <th style="padding-right: 10px;">Functions</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model.PagedList.Items)
            {
                <tr>
                    <td style="padding-right: 10px;">@item.Id</td>
                    <td style="padding-right: 10px;">@item.Name</td>
                    <td style="padding-right: 10px;">@item.AddedAt</td>
                    <td style="padding-right: 10px;">
                        <form method="post" asp-page-handler="Delete" style="display: inline">
                            <input type="hidden" name="id" value="@item.Id" />
                            <input type="submit" value="Hard Delete" />
                        </form>
                        <form method="post" asp-page-handler="SoftDelete" style="display: inline">
                            <input type="hidden" name="id" value="@item.Id" />
                            <input type="submit" value="Soft Delete" />
                        </form>
                    </td>
                </tr>
            }
            </tbody>
        </table>

        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @if (Model.PagedList.CurrentPage > 1)
                {
                    <li class="page-item">
                        <a class="page-link" asp-page="/Index">First</a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-page="/Index" asp-route-pageNum="@(Model.PagedList.CurrentPage - 1)" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                }
                
                @for (var page = Model.PagedList.StartPage; @page <= Model.PagedList.EndPage; @page++)
                {
                    if (page == Model.PagedList.CurrentPage)
                    {
                        <li class="page-item active" aria-current="page"><a class="page-link" href="#">@(page)</a></li>
                    }
                    else
                    {
                        <li class="page-item"><a class="page-link" asp-page="/Index" asp-route-pageNum="@(page)">@(page)</a></li>
                    }
                }
                
                @if (Model.PagedList.CurrentPage < Model.PagedList.TotalPages)
                {
                    <li class="page-item">
                        <a class="page-link" asp-page="/Index" asp-route-pageNum="@(Model.PagedList.CurrentPage + 1)" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" asp-page="/Index"  asp-route-pageNum="@Model.PagedList.TotalPages">Last</a>
                    </li>
                }
            </ul>
        </nav>
    </div>
</div>

Microsoft.EntityFrameworkCore.WebApplication/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Microsoft.EntityFrameworkCore.WebApplication</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
</head>
<body>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>